#!/bin/sh

MINENAME=beanmine
DBNAME=beanmine-dev

## add triggers
./gradlew generateUpdateTriggers
psql $DBNAME -f dbmodel/build/resources/main/add-update-triggers.sql

## do updates
echo "########## cdsreferenceupdater ${MINENAME}"
cd ~/java/ncgr/intermine
./cdsreferenceupdater $MINENAME

echo "########## transcriptreferenceupdater $MINENAME"
cd ~/java/ncgr/intermine
./transcriptreferenceupdater $MINENAME

echo "########## update genefamily.size $DBNAME ##########"
cd ~/$MINENAME
psql $DBNAME -c "UPDATE genefamily SET intermine_size = (SELECT count(*) FROM gene WHERE gene.genefamilyid=genefamily.id)"

## remove triggers
psql $DBNAME -f dbmodel/build/resources/main/remove-update-triggers.sql
