#!/bin/sh

echo ""
echo "##########################################################################################################################################"
echo "##########################################################################################################################################"
echo "##################################################### BEANMINE INTEGRATE #################################################################"
echo "##########################################################################################################################################"
echo "##########################################################################################################################################"
echo ""

## ontologies
./gradlew integrate -Psource=so --stacktrace
./gradlew integrate -Psource=go --stacktrace
./gradlew integrate -Psource=plant-ontology --stacktrace
./gradlew integrate -Psource=plant-trait-ontology --stacktrace
./gradlew integrate -Psource=bean-crop-ontology --stacktrace

## InterPro
./gradlew integrate -Psource=interpro --stacktrace
./gradlew integrate -Psource=interpro-go --stacktrace

## LIS gene families and phylotree
./gradlew integrate -Psource=legume.genefam.fam1.M65K --stacktrace
./gradlew integrate -Psource=legume.genefam.fam1.M65K.trees_ML_rooted --stacktrace

## phavu
./gradlew --stacktrace -Psource=phavu-about

## phavu.G19833.gnm1
./gradlew --stacktrace -Psource=G19833.gnm1.zBnF.genome_main
./gradlew --stacktrace -Psource=G19833.gnm1.ann1.pScz.cds
./gradlew --stacktrace -Psource=G19833.gnm1.ann1.pScz.gene_models_main
./gradlew --stacktrace -Psource=G19833.gnm1.ann1.pScz.info_annot
./gradlew --stacktrace -Psource=G19833.gnm1.ann1.pScz.protein
./gradlew --stacktrace -Psource=G19833.gnm1.ann1.pScz.transcript
./gradlew --stacktrace -Psource=G19833.gnm1.ann1.pScz.legfed_v1_0.M65K.gfa
./gradlew --stacktrace -Psource=G19833.gnm1.ann1.pScz.pathway
./gradlew --stacktrace -Psource=G19833.gnm1.ann1.expr.4ZDQ
./gradlew --stacktrace -Psource=G19833.gnm1.ann1.syn1.xQ7F
./gradlew --stacktrace -Psource=G19833.gnm1.mrk.Gaitan-Solis_Duque_2002
./gradlew --stacktrace -Psource=G19833.gnm1.mrk.Galeano_Fernandez_2011
./gradlew --stacktrace -Psource=G19833.gnm1.mrk.Parker_BernyMieryTeran_2020
./gradlew --stacktrace -Psource=G19833.gnm1.mrk.PvCookUCDavis2009
./gradlew --stacktrace -Psource=G19833.gnm1.mrk.Raggi_Caproni_2019

# ## phavu.G19833.gnm2
# ./gradlew --stacktrace -Psource=G19833.gnm2.fC0g.genome_main
# ./gradlew --stacktrace -Psource=G19833.gnm2.ann1.PB8d.cds
# ./gradlew --stacktrace -Psource=G19833.gnm2.ann1.PB8d.gene_models_main
# ./gradlew --stacktrace -Psource=G19833.gnm2.ann1.PB8d.info_annot
# ./gradlew --stacktrace -Psource=G19833.gnm2.ann1.PB8d.legfed_v1_0.M65K.gfa
# ./gradlew --stacktrace -Psource=G19833.gnm2.ann1.PB8d.pathway
# ./gradlew --stacktrace -Psource=G19833.gnm2.ann1.PB8d.protein
# ./gradlew --stacktrace -Psource=G19833.gnm2.ann1.PB8d.transcript
# ./gradlew --stacktrace -Psource=G19833.gnm2.ann1.syn1.DVDW

# ## phavu.UI111.gnm1
# ./gradlew --stacktrace -Psource=UI111.gnm1.3VTM.genome_main
# ./gradlew --stacktrace -Psource=UI111.gnm1.ann1.8L4N.cds
# ./gradlew --stacktrace -Psource=UI111.gnm1.ann1.8L4N.gene_models_main
# ./gradlew --stacktrace -Psource=UI111.gnm1.ann1.8L4N.info_annot
# ./gradlew --stacktrace -Psource=UI111.gnm1.ann1.8L4N.legfed_v1_0.M65K.gfa
# ./gradlew --stacktrace -Psource=UI111.gnm1.ann1.8L4N.legfed_v1_0.M65K.pathway
# ./gradlew --stacktrace -Psource=UI111.gnm1.ann1.8L4N.protein
# ./gradlew --stacktrace -Psource=UI111.gnm1.ann1.8L4N.transcript

# ## phavu genetic
# ./gradlew --stacktrace -Psource=BAT93_x_JALOEEP558.gen.Blair_Cortés_2018
# ./gradlew --stacktrace -Psource=BAT93_x_JALOEEP558.gen.Caldas_Blair_2009
# ./gradlew --stacktrace -Psource=BAT93_x_JALOEEP558.gen.Freyre_Skroch_1998
# ./gradlew --stacktrace -Psource=BAT93_x_JALOEEP558.gen.McConnell_Mamidi_2010
# ./gradlew --stacktrace -Psource=Cerinza_x_G24404.gen.Blair_Iriarte_2006
# ./gradlew --stacktrace -Psource=DOR364_x_BAT477.gen.Blair_Galeano_2012
# ./gradlew --stacktrace -Psource=G2333_x_G19839.gen.Checa_Blair_2008
# ./gradlew --stacktrace -Psource=ICABunsi_x_SXB405.gen.Parker_BernyMierYTeran_2020
# ./gradlew --stacktrace -Psource=mixed.gen.Blair_Cortés_2018
# ./gradlew --stacktrace -Psource=mixed.gen.Galeano_Fernandez_2011
# ./gradlew --stacktrace -Psource=Stampede_x_RedHawk.gen.Song_Jia_2015
# ./gradlew --stacktrace -Psource=Xana_x_Cornell49242.gen.Gaitán-Solís_Duque_2002

# ## phavu gwas
# ./gradlew --stacktrace -Psource=mixed.gwas.Parker_BernyMierYTeran_2020
# ./gradlew --stacktrace -Psource=mixed.gwas.Raggi_Caproni_2019


# ## phalu
# ./gradlew --stacktrace -Psource=phalu-about

# ## phalu.G27455.gnm1
# ./gradlew --stacktrace -Psource=G27455.gnm1.7NXX.genome_main
# ./gradlew --stacktrace -Psource=G27455.gnm1.ann1.JD7C.cds
# ./gradlew --stacktrace -Psource=G27455.gnm1.ann1.JD7C.gff
# ./gradlew --stacktrace -Psource=G27455.gnm1.ann1.JD7C.protein
# ./gradlew --stacktrace -Psource=G27455.gnm1.ann1.JD7C.transcript
# ./gradlew --stacktrace -Psource=phalu.G27455.gnm1.ann1.JD7C.legfed_v1_0.M65K.gfa
# #./gradlew --stacktrace -Psource=phalu.G27455.gnm1.ann1.JD7C.legfed_v1_0.M65K.pathway

