#!/bin/sh

## clear the logs (quietly)
rm -f intermine.log

## echo a big marker so we can see when this run started in the scroll
echo "##################################################################################################"
echo "###################################### integrate #################################################"
echo "##################################################################################################"

## ontologies
# ./gradlew integrate -Psource=so --stacktrace
# ./gradlew integrate -Psource=go --stacktrace
# ./gradlew integrate -Psource=to --stacktrace
# ./gradlew integrate -Psource=po --stacktrace

## LIS chado
# ./gradlew integrate -Psource=lis-genomics --stacktrace
# ./gradlew integrate -Psource=lis-proteins --stacktrace
# ./gradlew integrate -Psource=lis-genetics --stacktrace
# ./gradlew integrate -Psource=lis-featureprop --stacktrace
# ./gradlew integrate -Psource=lis-genefamilies --stacktrace
# ./gradlew integrate -Psource=lis-reactome-file --stacktrace

## ---------------------------------------------------------------------------------------------------------
## - ALL of the chado loaders must be DONE before continuing, because identifiers are changed by SQL below -
## ---------------------------------------------------------------------------------------------------------

./gradlew generateUpdateTriggers
psql beanmine-dev -f dbmodel/build/resources/main/add-update-triggers.sql
#psql beanmine-dev -f ../legfed-intermine-sql/cleanup-chado-bugs.sql
psql beanmine-dev -f ../legfed-intermine-sql/update-organism-genus-species.sql
psql beanmine-dev -f ../legfed-intermine-sql/update-organism-descriptions.sql
psql beanmine-dev -f ../legfed-intermine-sql/update-strain-descriptions.sql
#psql beanmine-dev -f ../legfed-intermine-sql/update-identifiers.sql
psql beanmine-dev -f dbmodel/build/resources/main/remove-update-triggers.sql

## file sources
#./gradlew integrate -Psource=beans-qtl-ontology --stacktrace
#./gradlew integrate -Psource=beans-expression --stacktrace
