#!/bin/sh
rm -f intermine.log

echo ""
echo "##########################################################################################################################################"
echo "##########################################################################################################################################"
echo "########################################################## INTEGRATE #####################################################################"
echo "##########################################################################################################################################"
echo "##########################################################################################################################################"
echo ""

## ontologies and InterPro
./gradlew integrate -Psource=go --stacktrace
./gradlew integrate -Psource=so --stacktrace
./gradlew integrate -Psource=plant-ontology --stacktrace
./gradlew integrate -Psource=plant-trait-ontology --stacktrace
./gradlew integrate -Psource=interpro --stacktrace
./gradlew integrate -Psource=interpro-go --stacktrace

## LIS gene families
./gradlew integrate -Psource=lis.fam1-genefamily --stacktrace

###########
## phavu ##
###########

./gradlew integrate -Psource=phavu-about --stacktrace

## phavu.G19833.gnm1
./gradlew integrate -Psource=phavu.G19833.gnm1-chromosome-fasta --stacktrace
./gradlew integrate -Psource=phavu.G19833.gnm1.ann1-cds-fasta --stacktrace
./gradlew integrate -Psource=phavu.G19833.gnm1.ann1-gff --stacktrace
./gradlew integrate -Psource=phavu.G19833.gnm1.ann1-info-annot --stacktrace
./gradlew integrate -Psource=phavu.G19833.gnm1.ann1-protein-fasta --stacktrace
./gradlew integrate -Psource=phavu.G19833.gnm1.ann1-mrna-fasta --stacktrace
./gradlew integrate -Psource=phavu.G19833.gnm1.ann1-expression --stacktrace
./gradlew integrate -Psource=phavu.G19833.gnm1.ann1.syn1-synteny --stacktrace

## phavu.G19833.gnm2
./gradlew integrate -Psource=phavu.G19833.gnm2-chromosome-fasta --stacktrace
./gradlew integrate -Psource=phavu.G19833.gnm2.ann1-cds-fasta --stacktrace
./gradlew integrate -Psource=phavu.G19833.gnm2.ann1-gff --stacktrace
./gradlew integrate -Psource=phavu.G19833.gnm2.ann1-info-annot --stacktrace
./gradlew integrate -Psource=phavu.G19833.gnm2.ann1-protein-fasta --stacktrace
./gradlew integrate -Psource=phavu.G19833.gnm2.ann1-mrna-fasta --stacktrace
./gradlew integrate -Psource=phavu.G19833.gnm2.ann1.syn1-synteny --stacktrace

## phavu.UI111.gnm1
./gradlew integrate -Psource=phavu.UI111.gnm1-chromosome-fasta --stacktrace
./gradlew integrate -Psource=phavu.UI111.gnm1.ann1-cds-fasta --stacktrace
./gradlew integrate -Psource=phavu.UI111.gnm1.ann1-gff --stacktrace
./gradlew integrate -Psource=phavu.UI111.gnm1.ann1-info-annot --stacktrace
./gradlew integrate -Psource=phavu.UI111.gnm1.ann1-protein-fasta --stacktrace
./gradlew integrate -Psource=phavu.UI111.gnm1.ann1-mrna-fasta --stacktrace
