#!/bin/sh

## clear the logs (quietly)
rm -f intermine.log

## echo a big marker so we can see when this run started in the scroll
echo "##################################################################################################"
echo "##################################### postprocess ################################################"
echo "##################################################################################################"

# ## legfed
# ./gradlew postprocess -Pprocess=legfed-create-gene-flanking-regions
# ./gradlew postprocess -Pprocess=legfed-create-go-annotations
# ./gradlew postprocess -Pprocess=legfed-create-intron-features
# ./gradlew postprocess -Pprocess=legfed-create-ontology-parent-annotations
# ./gradlew postprocess -Pprocess=legfed-create-exon-gene-references
# ./gradlew postprocess -Pprocess=legfed-create-protein-gene-references
# ./gradlew postprocess -Pprocess=legfed-create-supercontig-flanking-regions
# ./gradlew postprocess -Pprocess=legfed-populate-gene-spanning-qtls
# ./gradlew postprocess -Pprocess=legfed-populate-interpro-data
# ./gradlew postprocess -Pprocess=legfed-populate-linkagegroup-lengths
# ./gradlew postprocess -Pprocess=legfed-populate-publications

# ## more features
# ./gradlew postprocess -Pprocess=create-intergenic-region-features

# ## create various references and collections
# ./gradlew postprocess -Pprocess=populate-child-features
# ./gradlew postprocess -Pprocess=create-references
# ./gradlew postprocess -Pprocess=create-chromosome-locations-and-lengths
# ./gradlew postprocess -Pprocess=transfer-sequences

# ## views and indexes, after all data is set
# ./gradlew postprocess -Pprocess=create-location-overlap-index
# ./gradlew postprocess -Pprocess=create-overlap-view

# ## these must be run after any data is changed
# ./gradlew postprocess -Pprocess=create-attribute-indexes --stacktrace
./gradlew postprocess -Pprocess=summarise-objectstore

## these require Solr server
./gradlew postprocess -Pprocess=create-autocomplete-index
./gradlew postprocess -Pprocess=create-search-index

