#!/bin/sh
rm -f *.log

## echo a big marker so we can see when this run started in the scroll
echo ""
echo "##################################################################################################"
echo "##################################################################################################"
echo "##################################### postprocess ################################################"
echo "##################################################################################################"
echo "##################################################################################################"
echo ""

# ## IM CORE
# ./gradlew postprocess -Pprocess=do-sources
# ./gradlew postprocess -Pprocess=create-utr-references
# ./gradlew postprocess -Pprocess=create-references
# ./gradlew postprocess -Pprocess=make-spanning-locations
# ./gradlew postprocess -Pprocess=create-chromosome-locations-and-lengths
# ./gradlew postprocess -Pprocess=create-intergenic-region-features
# ./gradlew postprocess -Pprocess=transfer-sequences
# ./gradlew postprocess -Pprocess=populate-child-features
# ./gradlew postprocess -Pprocess=create-gene-flanking-features

# ## LIS
# ./gradlew postprocess -Pprocess=lis-create-cds-gene-references
# ./gradlew postprocess -Pprocess=lis-create-cds-protein-references
# ./gradlew postprocess -Pprocess=lis-create-cds-transcript-references
# ./gradlew postprocess -Pprocess=lis-create-gene-protein-collections
# ./gradlew postprocess -Pprocess=lis-create-transcript-gene-references
# ./gradlew postprocess -Pprocess=lis-create-transcript-protein-references
# ./gradlew postprocess -Pprocess=lis-populate-publications

# ## VIEWS AND INDEXES
# ./gradlew postprocess -Pprocess=create-location-overlap-index
# ./gradlew postprocess -Pprocess=create-overlap-view
# ./gradlew postprocess -Pprocess=create-attribute-indexes

## DO THESE AFTER UPDATES
./gradlew postprocess -Pprocess=summarise-objectstore
./gradlew postprocess -Pprocess=create-autocomplete-index
./gradlew postprocess -Pprocess=create-search-index
