#!/bin/sh
java -cp webapp/build/classes/java/main:libs/json-20180813.jar:/usr/share/java/commons-httpclient.jar:/usr/share/java/commons-logging.jar:/usr/share/java/commons-codec.jar:/usr/share/java/log4j-1.2.17.jar:/usr/share/java/apache-commons-lang.jar:/usr/share/java/antlr.jar \
       	beanmine.QueryClient
