#!/bin/sh
echo "----- MINE -----"
git status
echo "----- WEBAPP MODEL -----"
cd webapp/src/main/webapp/model; git status; cd -
echo "----- WEBAPP JAVA -----"
cd webapp/src/main/java; git status; cd -
