#!/bin/sh
echo "********** beanmine/integrate **********"
ant clean
ant -Dsource=so,go,chado-genomics,chado-genetics,chado-featureprop,chado-homology,chado-reactome-file,chado-go,beans-expression,entrez-organism
